### PR TITLE
test(monorepo): normalize psalm config file

### PR DESCRIPTION
**Pull request by szepeviktor**
I'm sorry. XML is not for humans.

### CODE REVIEW

**Comment by szepeviktor** [comment]
BTW PHPStan has a [neon](https://ne-on.org/) config (for humans).

**Comment by szepeviktor** [comment]
I'm not able to remember that a perfect English sentence is not suitable for comment.
Please fix my commit msg.

**Comment by szepeviktor** [comment]
@calvinalkan It takes the same amount of time to format commit msgs!

**Comment by calvinalkan** [comment]
> @calvinalkan It takes the same amount of time to format commit msgs as sending code changes!

I understand. It's vital for this project tho as all releases are done automatically based on commit messages using semantic-release. 

You can run `npm run commit` to get an interactive commit tool. 
(https://github.com/snicco/snicco/blob/master/CONTRIBUTING.md#commit-message-guidelines)

But tbh once I did 10 commits it because very easy and I'd never trade that for all the benefits semantic-release gives me.

Your commit here should probably be:

`chore(monorepo): normalize psalm config file`

If you don't want to bother with it don't worry, just leave the PRs as is and I ll merge them all in one go.

**Comment by szepeviktor** [comment]
Thank you!

Commit/PR message checking and blocking cases an emotional shock to me - and maybe other contributors.

**Comment by szepeviktor** [comment]
I'm a maintainer for a handful of GitHub repos.
People "do not like" Speech Police: so do not expect many contributors here in snicco.

**Comment by calvinalkan** [comment]
> Thank you!
> 
> Commit/PR message checking and blocking cases an emotional shock to me - and maybe other contributors.
> 
> 👮🏻‍♀️ It is like Speech Police.

@szepeviktor Thanks for the honest feedback. 

As we had previously only had internal contributors this was not an issue yet. 

Let me see if I can remove restrictions around the case and some other "visual only" stuff.

`<type>(<scope>): ` prefix is an absolute necessity tho as our entire build pipeline depends on it.

**Comment by calvinalkan** [comment]
> I'm a maintainer for a handful of GitHub repos. People "do not like" Speech Police: so do not expect many [contributors](https://github.com/snicco/snicco/graphs/contributors) here in snicco.

Thanks again for the feedback. I'll make some changes in the next days so that its more friendly to contribute for people not familiar with semantic release.

**Pull request closed without merging**
