### PR TITLE
chore(monorepo): add warning for contributors sending pr-s

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
# ⚡ 

GitHub has no UI for fixing commit msgs.

**Comment by szepeviktor** [comment]
> subject must be lower-case [subject-case]

**Comment by calvinalkan** [comment]
> # ⚡
> 
> GitHub has no UI for fixing commit msgs.
> 
> For a oneliner you have to git-fetch, git-checkout, git commit --ammend, gitpush -f

@szepeviktor I did not consider that. I never do git commits or PRs in the GitHub UI. A PR template looks like a good idea. 

All the rules are documented in [Contributing.md](https://github.com/snicco/snicco/blob/master/CONTRIBUTING.md#commit-message-guidelines). I ll create a TL;DR out of this and put it into the PR template

**Comment by szepeviktor** [comment]
> All the rules are documented in [Contributing.md](https://github.com/snicco/snicco/blob/master/CONTRIBUTING.md#commit-message-guidelines).

If you contribute to 20 repositories (or 100) you simply forget about that a nice English sentence gets you a ❌

**Pull request closed without merging**
