### PR TITLE
docs(templating): fix link in readme

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by calvinalkan** [comment]
@szepeviktor Hi,

could you rebase and edit the commit message so that its compliant with:

https://github.com/snicco/snicco/blob/master/CONTRIBUTING.md#commit-message-format

there are a lot of automations dependent on this commit message format.

Alternatively I can also rebase the branch.

**Comment by szepeviktor** [comment]
@calvinalkan Done 🍏

**Comment by szepeviktor** [comment]
@calvinalkan Please consider adding a TL;DR section to CONTRIBUTING.md with 2 lines.

1. the structure of commit messages
2. an example

**Comment by calvinalkan** [comment]
@szepeviktor thanks for the suggestion, noted. #145

**Pull request closed without merging**
